services:
  webapp:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file: .env

  scraper:
    build:
      context: .
      dockerfile: apps/services/Dockerfile
    env_file: .env

  scheduler:
    build:
      context: .
      dockerfile: apps/services/Dockerfile
    command: npm run cron
    env_file: .env