version: '3.8'

services:
  services:
    build:
      context: .
      dockerfile: apps/services/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8001:8001" 
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  webapp:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - SERVICES_API_URL=http://services:8001
      - NEXT_PUBLIC_URL=http://localhost:3001
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      services:
        condition: service_healthy
    env_file:
      - .env 